version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/cloud-storage
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: npm install --no-package-lock
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: add service account for GCP
          command: |
            echo ${GCP_CREDENTIALS} | base64 --decode --ignore-garbage > ${HOME}/cloud-storage/test/e2e/gcp_key.json
      - run:
          name: unit tests
          command: npm test
      - run:
          name: E2E tests
          command: npm run e2e
      - run:
          name: generate junit report
          command: |
            npm run junit-report
            npm run junit-report-e2e
            mkdir -p ./test_results/tape ./test_results/E2E
            mv test_results.xml ./test_results/tape/results.xml
            mv e2e_results.xml ./test_results/E2E/results.xml
      - store_artifacts:
          path: test_results
          destination: tests
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test_results
      - run:
          name: upload test report to codecov.io
          command: ./node_modules/.bin/codecov



